// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ReliabilityTest.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_RELIABILITYTEST_H_
#define _FAST_DDS_GENERATED_RELIABILITYTEST_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RELIABILITYTEST_SOURCE)
#define RELIABILITYTEST_DllAPI __declspec( dllexport )
#else
#define RELIABILITYTEST_DllAPI __declspec( dllimport )
#endif // RELIABILITYTEST_SOURCE
#else
#define RELIABILITYTEST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RELIABILITYTEST_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure TestData defined by the user in the IDL file.
 * @ingroup ReliabilityTest
 */
class TestData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TestData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TestData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TestData that will be copied.
     */
    eProsima_user_DllExport TestData(
            const TestData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TestData that will be copied.
     */
    eProsima_user_DllExport TestData(
            TestData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TestData that will be copied.
     */
    eProsima_user_DllExport TestData& operator =(
            const TestData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TestData that will be copied.
     */
    eProsima_user_DllExport TestData& operator =(
            TestData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x TestData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TestData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x TestData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TestData& x) const;

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp);

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp();


    /*!
     * @brief This function sets a value in member sequence_number
     * @param _sequence_number New value for member sequence_number
     */
    eProsima_user_DllExport void sequence_number(
            uint32_t _sequence_number);

    /*!
     * @brief This function returns the value of member sequence_number
     * @return Value of member sequence_number
     */
    eProsima_user_DllExport uint32_t sequence_number() const;

    /*!
     * @brief This function returns a reference to member sequence_number
     * @return Reference to member sequence_number
     */
    eProsima_user_DllExport uint32_t& sequence_number();


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message();


    /*!
     * @brief This function sets a value in member is_critical
     * @param _is_critical New value for member is_critical
     */
    eProsima_user_DllExport void is_critical(
            bool _is_critical);

    /*!
     * @brief This function returns the value of member is_critical
     * @return Value of member is_critical
     */
    eProsima_user_DllExport bool is_critical() const;

    /*!
     * @brief This function returns a reference to member is_critical
     * @return Reference to member is_critical
     */
    eProsima_user_DllExport bool& is_critical();

private:

    uint64_t m_timestamp{0};
    uint32_t m_sequence_number{0};
    std::string m_message;
    bool m_is_critical{false};

};

#endif // _FAST_DDS_GENERATED_RELIABILITYTEST_H_



